# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- develop

variables:
  artifactName: Luminis.AzureStorageBackup

stages:
- stage: Build
 
  jobs:
  - job: Build
    displayName: Build the package
    pool:
      vmImage: 'windows-latest'

    variables:
      buildConfiguration: 'Release'
      buildPlatform: 'Any CPU'
      solution: '**/*.sln'

    steps:
    - task: GitVersion@5
      inputs:
        runtime: 'full'
        updateAssemblyInfo: true
        additionalArguments: '/output buildserver'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        configuration: '$(buildConfiguration)'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'GitVersion.NuGetVersionV2'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(artifactName)
